name: Test code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Install br
        uses: browser-actions/setup-chrome@v1
      - name: run chrome
        run: chrome --version
      - name: Test
        run: npm run test
